Feature/extract values from advanced search fields
SGS-Optimisation/PM-Search-2 pull request #27
Opened 2023-07-10 12:38 UTC by Khushboo-5157

extracting values from advancedSearchFields

2023-07-11 07:23 UTC, yayann requested changes

2023-07-11 07:23 UTC, yayann commented on app/Services/Search/WebServices/TextSearchWebService.php
> +            foreach ($data->fields as $key => $value) {
Please add a parameter here to toggle this behaviour on and off from the backend. Check the NovaServiceProvider, and add a boolean param like "Force Convert Advanced To Simple Search"

2023-07-13 08:03 UTC, yayann requested changes

2023-07-13 08:03 UTC, yayann commented on resources/views/app.blade.php
> +                                  'convert_advancedSearch_to_simpleSearch' => nova_get_setting('convert_advancedSearch_to_simpleSearch'),
this doesn't need to go here, it's only required in backend

2023-07-13 08:03 UTC, yayann commented on app/Services/Search/WebServices/TextSearchWebService.php
> +            foreach ($data->fields as $key => $value) {
@Khushboo-5157 you should do something like 
```
if (nova_get_setting('convert_advancedSearch_to_simpleSearch')) {
    /// new code to force simple search
} else {
    // old code to run search including advanced
}
```

2023-07-13 08:33 UTC, Khushboo-5157 commented on resources/views/app.blade.php
> +                                  'convert_advancedSearch_to_simpleSearch' => nova_get_setting('convert_advancedSearch_to_simpleSearch'),
done, removed from here

2023-07-13 08:45 UTC, yayann requested changes

2023-07-13 08:45 UTC, yayann commented on app/Providers/NovaServiceProvider.php
> +                Boolean::make('Force Convert Advanced To Simple Search', 'convert_advancedSearch_to_simpleSearch')
Just realised this would put this feature under the "matomo" panel. Just add another panel with
```
Panel::make('Search Options', [ 
    Boolean::make('Force Convert Advanced To Simple Search', 'convert_advancedSearch_to_simpleSearch')
]);
```
This should be outside of the matomo panel

2023-07-13 09:18 UTC, Khushboo-5157 commented on app/Providers/NovaServiceProvider.php
> +                Boolean::make('Force Convert Advanced To Simple Search', 'convert_advancedSearch_to_simpleSearch')
done, please have a look

2023-07-13 09:23 UTC, yayann approved these changes

2023-07-13 09:24 UTC, merged