Fix/us 206991 adding simplified customer name to advanced search
SGS-Optimisation/PM-Search-2 pull request #47
Opened 2023-12-04 13:50 UTC by Khushboo-5157

contains changes for adding simplified customer name to advanced search -- US-206991

2023-12-05 07:31 UTC, yayann requested changes

2023-12-05 07:31 UTC, yayann commented on app/Services/Search/TextSearchCreationService.php
> -            'searchparameters' => ['textsearch' => 'Y', 'advanced_search' => count($this->advanced_fields) > 0 ? 'Y' : 'N'],
We should probably not always force the advanced search mode, e.g. if it's an internal user. Keep the count check and also add on a verification that the user making the request is a client. You might want to write a function elsewhere in this class to do this verification and make this test more legible.

2023-12-05 07:31 UTC, yayann commented on app/Services/Search/TextSearchCreationService.php
> +            'fields' => ['simplified_group_name' => $this->user->simplified_customer_group],
This should only be added in case the user is a customer.

2023-12-05 07:31 UTC, yayann commented on app/Services/Search/TextSearchCreationService.php
> +                    if (!in_array($field, array_keys(config('pm-search.advanced_search')))) {
This line was what introduced a bug on advanced search, the `if (!$field)` was the fix
```suggestion
                   
```

2023-12-05 07:31 UTC, yayann commented on resources/js/Pages/Search/Pending.vue
> +                                    <template v-for="(value, field) in search.search_data.fields">
The clients will probably have access to only the simple search, so we might not need changes to the tag/advanced search.

2023-12-05 12:15 UTC, Khushboo-5157 commented on app/Services/Search/TextSearchCreationService.php
> -            'searchparameters' => ['textsearch' => 'Y', 'advanced_search' => count($this->advanced_fields) > 0 ? 'Y' : 'N'],
I have created a new function hasAdvancedFields(), please have a look

2023-12-05 12:15 UTC, Khushboo-5157 commented on app/Services/Search/TextSearchCreationService.php
> +            'fields' => ['simplified_group_name' => $this->user->simplified_customer_group],
fixed this, please check

2023-12-05 12:16 UTC, Khushboo-5157 commented on app/Services/Search/TextSearchCreationService.php
> +                    if (!in_array($field, array_keys(config('pm-search.advanced_search')))) {
reverted the fix, please check now

2023-12-06 09:10 UTC, yayann approved these changes

2023-12-06 09:13 UTC, merged