Adding capability for "new search" on results page.
SGS-Optimisation/PM-Search-2 pull request #5
Opened 2023-04-27 11:44 UTC by Khushboo-5157

Changes to add new search capability on results page.

2023-04-27 12:15 UTC, yayann commented on resources/js/Components/Search/TextSearchComponent.vue
> +        for (var key in Object.keys(props.initialValues)) {
Instead of using a for loop here, you could probably access the object keys by name, since they are always the same: `textsearchstrings` and `fields`. Might make the code clearer

2023-04-27 12:26 UTC, yayann commented on resources/js/Components/Search/TextSearchComponent.vue
> +                }
In this block, you want to take only the items in the `props.initialValues.textsearchstrings` which do not contain a `:`. 
Also, check that you are appending to the `tags` array, seems you are overriding the value each time here

2023-04-27 12:36 UTC, yayann commented on resources/js/Components/Search/TextSearchComponent.vue
> +                }
You need to convert the `key` to its short form, something like
`configStore.getAdvancedSearchFields()[key].key`

After the loop, you'll want to call `handleChangeTag`, this takes an array and updates the value to `tags`. So you might want to work with a different variable in this whole block, not directly with `tags.value`.

2023-04-27 12:38 UTC, yayann commented on resources/js/Components/Search/TextSearchComponent.vue
> +                }
The handleChangeTag also takes any `<field>:<value>` and properly populates the advanced search form, which will solve your issue.

2023-04-28 10:02 UTC, Khushboo-5157 commented on resources/js/Components/Search/TextSearchComponent.vue
> +        for (var key in Object.keys(props.initialValues)) {
Implemented that way. But it has repetition of loops. Let me know if this is fine.

2023-04-28 10:02 UTC, Khushboo-5157 commented on resources/js/Components/Search/TextSearchComponent.vue
> +                }
I changed to .push instead of "="

2023-04-28 10:08 UTC, Khushboo-5157 commented on resources/js/Components/Search/TextSearchComponent.vue
> +                }
Adding handleChangeTag function at the end and removing "for loop" from line 148 fixed the issue.

2023-05-02 09:54 UTC, yayann requested changes

2023-05-02 09:54 UTC, yayann commented on resources/js/Components/Search/TextSearchComponent.vue
> +            for (var field in Object.entries(props.initialValues.fields)) {
The use of `Object.entries` and `Object.values` here is not necessary and only make the code harder to read. 
![Screenshot 2023-05-02 at 13 40 09](https://user-images.githubusercontent.com/204421/235633325-f1c0214c-f251-4b2f-a6ad-3b59b74e532b.png)
<img width="478" alt="Screenshot 2023-05-02 at 13 40 27" src="https://user-images.githubusercontent.com/204421/235633341-1286fd82-cd7d-44c2-8f07-b13659166d73.png">

Above I added a for loop just to show you what happens when recursing on the object itself, and what the keys you get are in the console log. With direct recursion on the object, you get the actual key name, whereas with entries you get an index

2023-05-02 09:54 UTC, yayann commented on resources/js/Components/Search/TextSearchComponent.vue
> +                        tags.value.push(configStore.getAdvancedSearchFields()[Object.keys(props.initialValues.fields)[field]].key + ': ' + value);
<img width="480" alt="Screenshot 2023-05-02 at 13 46 24" src="https://user-images.githubusercontent.com/204421/235634313-579361f3-ccb1-40df-9817-adfe69ce66ea.png">
This is how the date is stored by the calendar component.  
You'll probably want to use the full string instead of the sliced one, e.g:  
`const dates_array = JSON.parse(props.initialValues.fields.booked_date)`

You then convert the strings into actual javascript dates ( `new Date(date_str)` ).

2023-05-02 11:13 UTC, Khushboo-5157 commented on resources/js/Components/Search/TextSearchComponent.vue
> +                        tags.value.push(configStore.getAdvancedSearchFields()[Object.keys(props.initialValues.fields)[field]].key + ': ' + value);
fixed as suggested. Please have a look.

2023-05-02 11:13 UTC, Khushboo-5157 commented on resources/js/Components/Search/TextSearchComponent.vue
> +            for (var field in Object.entries(props.initialValues.fields)) {
fixed as suggested. Please have a look.

2023-05-02 15:54 UTC, merged